### PR TITLE
Add mouse configuration options

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**

### CODE REVIEW

**Comment by toast003** [comment]
Thanks for the pr!

Haven't tested but so far everything looks good minus commit [6a76b3f](https://github.com/toast003/plasma-manager/pull/1/commits/6a76b3ff0972aca8886d9e96f960d39bedca873e), since we do the hex to decimal conversion in `write_config.py` now.

**Comment by HeitorAugustoLN** [comment]
Oh, i didn't know that.

**Comment by HeitorAugustoLN** [comment]
I updated because the touchpad examples were in decimal too.

**Comment by toast003** [comment]
Oooh I must have forgot to change them over then, my bad

**Comment by HeitorAugustoLN** [comment]
I will revert 6a76b3f

**Pull request merged**
